GET https://personal-finance-server.onrender.com/api/users

###

GET https://personal-finance-server.onrender.com/api/transactions

###

GET https://personal-finance-server.onrender.com/api/budgets/transactions

###

POST https://personal-finance-server.onrender.com/api/login
Content-Type: application/json

{
  "email": "admin@test.com",
  "password": "091184"
}

###

POST https://personal-finance-server.onrender.com/api/register
Content-Type: application/json

{
  "name": "Test",
  "email": "test@test.com",
  "password": "111111"
}

